--CREATE DATA BASE
CREATE DATABASE UNIVERSITY_DB;
USE UNIVERSITY_DB;
--CREATE TABLE 
CREATE TABLE EMPLOYEE_DETAILS(EMP_ID INT PRIMARY KEY,
							  EMP_FIRST_NAME VARCHAR(20) NOT NULL,
							  EMP_LAST_NAME VARCHAR(20) NOT NULL,
							  EMP_ADDRESS VARCHAR(30),
							  EMP_MOBILE_NO INTEGER NOT NULL,
							  EMP_CITY VARCHAR(15) NOT NULL);

INSERT INTO EMPLOYEE_DETAILS (EMP_FIRST_NAME,EMP_LAST_NAME,EMP_ADDRESS,EMP_ADDRESS,EMP) VALUES(2,'MOAZAM','AZEEM','HOME',0324406406,'LAHORE');
UPDATE EMPLOYEE_DETAILS SET EMP_ADDRESS = 'HOME1' WHERE EMP_ID = 2;
DELETE FROM EMPLOYEE_DETAILS WHERE EMP_ID = 2;

SELECT *FROM EMPLOYEE_DETAILS;