--CREATE DATABASE
CREATE DATABASE UNI_GROUP_DB;

--WORK IN UNI_GROUP_DB
USE UNI_GROUP_DB;

--CREATE TABLE
CREATE TABLE MEMBERS_INFO(M_ID INT IDENTITY(1,1) PRIMARY KEY, 
						  M_NAME VARCHAR(30) NOT NULL,
						  M_AGE INT NOT NULL,
						  M_LANGUAGE VARCHAR(50) NOT NULL,
						  M_NO VARCHAR(14) NOT NULL,
						  M_WEB_SITES VARCHAR(255));

--IF WE WANT TO UPDATE YOUR TABLE FIELDS
ALTER TABLE MEMBERS_INFO ADD SALARY INT;

--INSERT DATA IN FILES
INSERT INTO MEMBERS_INFO VALUES('AZEEM',20,'PYTHON',03244064060,'AJWEB.TK');
INSERT INTO MEMBERS_INFO VALUES('UMER',20,'PYTHON',03244064070,'TECNO.COM');
INSERT INTO MEMBERS_INFO VALUES('MUZAMIL',20,'PYTHON',03244064080,'TECNO.COM');

--IF WE WANT TO UPDATE ANY FIELD
UPDATE MEMBERS_INFO SET M_LANGUAGE = 'JAVA' WHERE M_ID = 2;
UPDATE MEMBERS_INFO SET M_AGE = 21 WHERE M_ID = 1;
UPDATE MEMBERS_INFO SET SALARY = 15000;

--IF WE WANT TO DELETE ANY ROW/RECORD
DELETE FROM MEMBERS_INFO WHERE M_ID = 1;

--IF WE WANT TO DELETE ALL TABLE
DELETE FROM MEMBERS_INFO; 

--SELECT COMMENDS
SELECT *FROM MEMBERS_INFO WHERE M_AGE = 20;
SELECT *FROM MEMBERS_INFO WHERE M_AGE = 21;

--SELECT SPECIFIC COLUMN
SELECT M_NAME FROM MEMBERS_INFO;

--SELECT ALL TABLE
SELECT *FROM MEMBERS_INFO;

--SUM COMMAND 
SELECT SUM(SALARY) FROM MEMBERS_INFO;