CREATE DATABASE EMAIL_INFO;

USE EMAIL_INFO;

CREATE TABLE EMAIL(ID INTEGER PRIMARY KEY,
				   USERNAME VARCHAR(20) NOT NULL,
				   EMAIL VARCHAR(20) NOT NULL,
				   PASSWORD INTEGER NOT NULL)

INSERT INTO EMAIL VALUES(1,'AZEEM','AZEEMAJ101@GAMIL.COM',2765);
INSERT INTO EMAIL VALUES(2,'AZEEM1','AZEEMAJ101@GAMIL.COM',2765);
INSERT INTO EMAIL VALUES(3,'AZEEM2','AZEEMAJ101@GAMIL.COM',2765);
INSERT INTO EMAIL VALUES(4,'AZEEM3','AZEEMAJ101@GAMIL.COM',2765);

UPDATE EMAIL SET PASSWORD = 27653 WHERE USERNAME = 'AZEEM3';

SELECT *FROM EMAIL WHERE EMAIL = 'AZEEM1@GMAIL.COM' AND PASSWORD = 27651;