CREATE DATABASE T_DB;
USE T_DB

CREATE TABLE PERSON (P_ID INT IDENTITY(1,1) PRIMARY KEY,
					 P_NAME VARCHAR(60),
					 CITY VARCHAR(50)
					 );
CREATE TABLE ORDERS (O_ID INT NOT NULL PRIMARY KEY,
					 ITEM VARCHAR(50) NOT NULL,
					 P_ID INT FOREIGN KEY REFERENCES PERSON (P_ID));
INSERT INTO PERSON VALUES('AZEEM3','LHR');
INSERT INTO PERSON VALUES('AZEEM','LHR');

INSERT INTO PERSON VALUES('AZEEM1','LHR');
INSERT INTO PERSON VALUES('AZEEM2','LHR');

INSERT INTO ORDERS VALUES(5,'BOOK1',1);
INSERT INTO ORDERS VALUES(2,'CMP',2);
INSERT INTO ORDERS VALUES(3,'MOBILE',3);
INSERT INTO ORDERS VALUES(8,'BOOK2',8);

INSERT INTO ORDERS VALUES(7,'BOOK1', null);
DELETE FROM ORDERS WHERE P_ID = 8;
ALTER TABLE ORDERS DROP CONSTRAINT FK__ORDERS__P_ID__3B75D760;
ALTER TABLE ORDERS ADD FOREIGN KEY (P_ID) REFERENCES PERSON(P_ID);
SELECT *FROM PERSON;
SELECT *FROM ORDERS;

