CREATE DATABASE AREEBA;

USE SCHOOL_DB;

CREATE TABLE STUDENTS (Student_id int identity(1,1) CONSTRAINT Stud_Info PRIMARY KEY,
					   NAME VARCHAR(40) NOT NULL,
					   ROLLNUMBER INT UNIQUE,
					   EMAIL VARCHAR(50) DEFAULT 'XYZ@ABC.COM',
					   MOBILE VARCHAR(13) NOT NULL,
					   CITY VARCHAR(13),
					   DEPARTMENTID INT
					   FOREIGN KEY(DEPARTMENTID) REFERENCES Departments(DEPARTMENTID),
					   SUBJECTID INT
					   FOREIGN KEY(SUBJECTID) REFERENCES Subjects(SUBJECTID)
					   );

CREATE TABLE Departments (DEPARTMENTID INT IDENTITY(1,1) PRIMARY KEY,
						  DNAME VARCHAR(50) NOT NULL);

CREATE TABLE Subjects (SUBJECTID INT IDENTITY(1,1) PRIMARY KEY,
						  SNAME VARCHAR(50) NOT NULL);

INSERT INTO Departments VALUES ('BSCS');
INSERT INTO Departments VALUES ('BSSE');
INSERT INTO Departments VALUES ('BSIT');
INSERT INTO Departments VALUES ('BS-ENGLISH');
INSERT INTO Departments VALUES ('BS-URDU');
INSERT INTO Departments VALUES ('BS-MATH');
INSERT INTO Departments VALUES ('BSCS1');
INSERT INTO Departments VALUES ('BSCS2');
INSERT INTO Departments VALUES ('BSCS3');
INSERT INTO Departments VALUES ('BSCS4');
INSERT INTO Departments VALUES ('BSCS5');
INSERT INTO Departments VALUES ('BSCS6');
INSERT INTO Departments VALUES ('BSCS7');
INSERT INTO Departments VALUES ('BSCS8');
INSERT INTO Departments VALUES ('BSCS9');
INSERT INTO Departments VALUES ('BSCS01');
INSERT INTO Departments VALUES ('BSCS02');
INSERT INTO Departments VALUES ('BSCS03');
INSERT INTO Departments VALUES ('BSCS04');
INSERT INTO Departments VALUES ('BSCS05');

INSERT INTO Subjects VALUES ('computer');
INSERT INTO Subjects VALUES ('computer1');
INSERT INTO Subjects VALUES ('computer2');
INSERT INTO Subjects VALUES ('computer3');
INSERT INTO Subjects VALUES ('computer4');
INSERT INTO Subjects VALUES ('computer5');
INSERT INTO Subjects VALUES ('computer6');
INSERT INTO Subjects VALUES ('computer7');
INSERT INTO Subjects VALUES ('computer8');
INSERT INTO Subjects VALUES ('computer9');
INSERT INTO Subjects VALUES ('computer01');
INSERT INTO Subjects VALUES ('computer02');
INSERT INTO Subjects VALUES ('computer03');
INSERT INTO Subjects VALUES ('computer04');
INSERT INTO Subjects VALUES ('computer05');
INSERT INTO Subjects VALUES ('computer06');
INSERT INTO Subjects VALUES ('computer07');
INSERT INTO Subjects VALUES ('computer08');
INSERT INTO Subjects VALUES ('computer09');
INSERT INTO Subjects VALUES ('urdu');


INSERT INTO STUDENTS VALUES('AREEBA',1,DEFAULT,03244064060,'LHR',1,1);
INSERT INTO STUDENTS VALUES('AREEBA',11,DEFAULT,03244064060,'LHR',2,1);
INSERT INTO STUDENTS VALUES('AREEBA',12,DEFAULT,03244064060,'LHR',1,3);
INSERT INTO STUDENTS VALUES('AREEBA',13,DEFAULT,03244064060,'LHR',2,1);
INSERT INTO STUDENTS VALUES('AREEBA',14,DEFAULT,03244064060,'LHR',1,3);
INSERT INTO STUDENTS VALUES('AREEBA',15,DEFAULT,03244064060,'LHR',6,1);
INSERT INTO STUDENTS VALUES('AREEBA',16,DEFAULT,03244064060,'LHR',1,7);
INSERT INTO STUDENTS VALUES('AREEBA',17,DEFAULT,03244064060,'LHR',2,1);
INSERT INTO STUDENTS VALUES('AREEBA',18,DEFAULT,03244064060,'LHR',1,5);
INSERT INTO STUDENTS VALUES('AREEBA',21,DEFAULT,03244064060,'LHR',6,3);
INSERT INTO STUDENTS VALUES('AREEBA',31,DEFAULT,03244064060,'LHR',6,2);
INSERT INTO STUDENTS VALUES('AREEBA',41,DEFAULT,03244064060,'LHR',4,5);
INSERT INTO STUDENTS VALUES('AREEBA',51,DEFAULT,03244064060,'LHR',6,3);
INSERT INTO STUDENTS VALUES('AREEBA',61,DEFAULT,03244064060,'LHR',12,13);
INSERT INTO STUDENTS VALUES('AREEBA',71,DEFAULT,03244064060,'LHR',15,14);
INSERT INTO STUDENTS VALUES('AREEBA',81,DEFAULT,03244064060,'LHR',16,14);
INSERT INTO STUDENTS VALUES('AREEBA',91,DEFAULT,03244064060,'LHR',13,14);
INSERT INTO STUDENTS VALUES('AREEBA',111,DEFAULT,03244064060,'LHR',13,14);
INSERT INTO STUDENTS VALUES('AREEBA',133,DEFAULT,03244064060,'LHR',13,15);
SELECT *FROM STUDENTS;

--Step 4
ALTER DATABASE SCHOOL_DB MODIFY NAME = AREEBA_MUNEEB;
--Step 5
ALTER TABLE STUDENTS DROP CONSTRAINT Stud_Info;
--Step 6
ALTER TABLE STUDENTS ADD CONSTRAINT Stud_Info PRIMARY KEY(Student_id);
--Step 7
ALTER TABLE STUDENTS DROP CONSTRAINT Stud_Info;
ALTER TABLE STUDENTS ADD CONSTRAINT Stud_Info PRIMARY KEY(Student_id, Name);

--Delete All Table
DROP TABLE Subjects;
DROP TABLE Departments;
DROP TABLE STUDENTS;

SELECT *FROM STUDENTS;
