CREATE DATABASE DB_FINAL;

USE DB_FINAL;

CREATE TABLE PARENT(ID INT IDENTITY(1,1) PRIMARY KEY,
					P_NAME VARCHAR(30) NOT NULL,
					P_CITY VARCHAR(20) CHECK (P_CITY = 'LAHORE') DEFAULT 'LAHORE',
					P_AGE INT CHECK(P_AGE >= 18 AND P_AGE <= 40));

CREATE TABLE CHILD(C_ID INT IDENTITY(1,1) PRIMARY KEY,
				   C_NAME VARCHAR(30) NOT NULL,
				   C_AGE INT CHECK(C_AGE < 18),
				   C_CITY VARCHAR(30) NOT NULL,
				   ID INT FOREIGN KEY REFERENCES PARENT(ID));

DROP TABLE CHILD
GO
ALTER TRIGGER IN_TABLE
ON PARENT
AFTER INSERT,UPDATE,DELETE
AS 
BEGIN
PRINT 'ADDED THIS ROW'
SELECT *FROM INSERTED
END

GO 
CREATE TRIGGER C_IN_TABLE
ON CHILD
AFTER INSERT,UPDATE,DELETE
AS
BEGIN
SELECT *FROM INSERTED
END

SELECT *FROM PARENT;
INSERT INTO PARENT VALUES('AZEEM','LAHORE',39);
INSERT INTO PARENT VALUES('AZEEM1','LAHORE',39);
INSERT INTO PARENT VALUES('AZEEM2','LAHORE',29);
INSERT INTO PARENT VALUES('AZEEM3','LAHORE',19);
INSERT INTO PARENT VALUES('AZEEM4','LAHORE',27);
INSERT INTO PARENT VALUES('AZEEM5','LAHORE',35);
INSERT INTO PARENT VALUES('AZEEM6','LAHORE',32);

GO
ALTER TRIGGER ON_TABLE
ON DATABASE
FOR CREATE_TABLE,ALTER_TABLE,DROP_TABLE
AS 
BEGIN
PRINT 'DDL Command Run'
END

GO
CREATE VIEW V_IN_TABLE
AS
SELECT *FROM CHILD

SELECT *FROM V_IN_TABLE
INSERT INTO V_IN_TABLE VALUES('Maryam1',10,'karachi',4);
INSERT INTO V_IN_TABLE VALUES('Maryam2',10,'karachi',5);
INSERT INTO V_IN_TABLE VALUES('Maryam3',10,'karachi',6);
INSERT INTO V_IN_TABLE VALUES('Maryam4',10,'karachi',4);
INSERT INTO V_IN_TABLE VALUES('Maryam5',10,'karachi',5);
DELETE FROM V_IN_TABLE WHERE C_NAME = 'MARYAM'
GO
CREATE TRIGGER C_IN_TABLE
ON CHILD
AFTER INSERT,UPDATE,DELETE
AS 
BEGIN
SELECT *FROM INSERTED
END

SELECT *FROM PARENT P LEFT OUTER JOIN CHILD C ON  P.ID = C.ID;
SELECT *FROM PARENT P RIGHT OUTER JOIN CHILD C ON  P.ID = C.ID;
SELECT *FROM PARENT P FULL OUTER JOIN CHILD C ON  P.ID = C.ID;
SELECT *FROM PARENT P INNER JOIN CHILD C ON  P.ID = C.ID where c_name like '%1%';


SELECT *FROM CHILD where c_id like '[1-8]%';
SELECT *FROM CHILD where c_name like '_1%';
SELECT *FROM CHILD WHERE ID IN (1,2,5);
SELECT *FROM CHILD WHERE C_NAME BETWEEN 'M' AND 'N'
SELECT *FROM CHILD WHERE C_ID BETWEEN 7 AND 10;
SELECT *FROM CHILD WHERE C_ID IN (7,10);


--SUB QUERIES
SELECT *FROM CHILD WHERE C_ID = (SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%1%');
SELECT *FROM CHILD WHERE C_ID = ANY(SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%M%');
SELECT *FROM CHILD WHERE C_ID IN(SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%M%');
SELECT *FROM CHILD WHERE C_ID = ALL(SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%M%');
SELECT TOP 2 *FROM CHILD WHERE C_ID = ANY(SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%M%');
SELECT COUNT(C_ID) AS TOTAL_ROWS FROM CHILD WHERE C_ID = ANY(SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%M%');
SELECT SUM(C_ID) AS TOTAL_ROWS FROM CHILD WHERE C_ID = ANY(SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%M%');
SELECT MAX(C_ID) AS TOTAL_ROWS FROM CHILD WHERE C_ID = ANY(SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%M%');
SELECT MIN(C_ID) AS TOTAL_ROWS FROM CHILD WHERE C_ID = ANY(SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%M%');
SELECT AVG(C_ID) AS TOTAL_ROWS FROM CHILD WHERE C_ID = ANY(SELECT C_ID FROM CHILD WHERE C_NAME LIKE '%M%');


SELECT COUNT(C.ID) AS [MATCH VALUES] FROM PARENT P INNER JOIN CHILD C ON  P.ID = C.ID 
where c_name like '[am]%' HAVING COUNT(C.ID) >= 1;
GO
ALTER PROC FUN (@N VARCHAR(30))
AS
BEGIN
SELECT *FROM PARENT P INNER JOIN CHILD C ON  P.ID = C.ID 
where c_name = @N;
END
DECLARE @N VARCHAR(30) = 'MARYAM1';
SELECT @N
EXEC FUN @N 

GO
ALTER PROC OUTP(@NAME VARCHAR(20), @COUNT INT OUTPUT)
AS 
BEGIN
SELECT @COUNT = COUNT(C_ID) FROM CHILD
SELECT @COUNT
END

DECLARE @COUNT0 INT
EXEC OUTP @NAME = 'MARYAM1', @COUNT = @COUNT0 OUTPUT;
SELECT @COUNT0

SELECT LEFT('SQL Tutorial', 5) AS ExtractString;
SELECT STUFF('SQL Tutorial', 1, 3, 'HTML');
SELECT TRUNK(456.5) FROM DUAL;
