CREATE DATABASE REDDROP;

USE REDDROP;

CREATE TABLE _LOGIN (LOGIN_ID INT IDENTITY(1,1) PRIMARY KEY,
					 EMAIL VARCHAR(50) NOT NULL,
					 PASSWORD VARCHAR(50) NOT NULL,
					 PIN VARCHAR(50) NOT NULL);

INSERT INTO _LOGIN VALUES('LOVE@GMAIL.COM','2765','1234'),('AZEEM@GMAIL.COM','2765','1234'),
						 
						 ('MARYAM@GMAIL.COM','2765','1234');
DROP TABLE _LOGIN
SELECT *FROM _LOGIN


CREATE TABLE _ADMIN (ADMIN_ID INT IDENTITY(1,1) PRIMARY KEY,
					 NAME VARCHAR(50) NOT NULL,
					 GENDER VARCHAR(20) NOT NULL,
					 LOGIN_ID INT FOREIGN KEY (LOGIN_ID) REFERENCES _LOGIN(LOGIN_ID) ON DELETE CASCADE);
DROP TABLE _ADMIN
INSERT INTO _ADMIN VALUES('AZEEM','MALE',2);
SELECT *FROM _ADMIN;
DELETE _ADMIN WHERE ADMIN_ID = 2;
CREATE TABLE _MANAGER (MANAGER_ID INT IDENTITY(1,1) PRIMARY KEY,
					 NAME VARCHAR(50) NOT NULL,
					 GENDER VARCHAR(20) NOT NULL,
					 LOGIN_ID INT FOREIGN KEY (LOGIN_ID) REFERENCES _LOGIN(LOGIN_ID) ON DELETE CASCADE);
INSERT INTO _MANAGER VALUES('LOVE','FEMALE',1);
SELECT *FROM _MANAGER;
drop table _MANAGER

CREATE TABLE _USERS (SID INT IDENTITY(1,1) PRIMARY KEY,
					 F_NAME VARCHAR(50) NOT NULL,
					 L_NAME VARCHAR(50) NOT NULL,
					 CONTACT VARCHAR(15) NOT NULL,
					 GENDER VARCHAR(20) NOT NULL,
					 DOB DATE NOT NULL,
					 BLOOD_GROUP VARCHAR(10) NOT NULL,
					 PROVINCE VARCHAR(30) NOT NULL,
					 CITY VARCHAR(30) NOT NULL,
					 ADDRESS VARCHAR(30) NOT NULL,
					 LOGIN_ID INT FOREIGN KEY (LOGIN_ID) REFERENCES _LOGIN(LOGIN_ID)ON DELETE CASCADE);

INSERT INTO _USERS VALUES('MARYAM','ASGHER','03244064060','FEMALE','2000-1-1','O+','PUNJAB','LAHORE','HOME',3);
SELECT *FROM _USERS;
DROP TABLE _USERS

SELECT *FROM _LOGIN,_ADMIN
WHERE _LOGIN.LOGIN_ID = _ADMIN.LOGIN_ID;

SELECT *FROM _LOGIN,_USERS
WHERE _LOGIN.LOGIN_ID = _USERS.LOGIN_ID;

SELECT *FROM _LOGIN,_MANAGER
WHERE _LOGIN.LOGIN_ID = _MANAGER.LOGIN_ID;

DELETE _LOGIN
WHERE _LOGIN.LOGIN_ID = 2;

DELETE _MANAGER
WHERE _MANAGER.MANAGER_ID = 1;

DELETE _LOGIN WHERE EMAIL = 'LOVE@GMAIL.COM';
DELETE _LOGIN, _MANAGER FROM _LOGIN WHERE _LOGIN.LOGIN_ID = _MANAGER.LOGIN_ID AND 