USE UNI_GROUP_DB;
SELECT *FROM MEMBERS_INFO;

SELECT CITY FROM MEMBERS_INFO WHERE M_ID = 3;

SELECT *FROM MEMBERS_INFO WHERE CITY = 'LAHORE';

SELECT *FROM MEMBERS_INFO WHERE CITY = (SELECT CITY FROM MEMBERS_INFO WHERE M_ID = 3);

SELECT *FROM MEMBERS_INFO WHERE MARITAL_STATUS = (SELECT MARITAL_STATUS FROM MEMBERS_INFO WHERE M_ID = 5);

SELECT *FROM MEMBERS_INFO WHERE SALARY > (SELECT AVG(SALARY) FROM MEMBERS_INFO);

SELECT *FROM MEMBERS_INFO WHERE M_ID >= (SELECT M_ID FROM MEMBERS_INFO WHERE M_ID = 4);

SELECT *FROM MEMBERS_INFO WHERE SALARY > (SELECT SALARY FROM MEMBERS_INFO WHERE M_ID = 4);


SELECT *FROM MEMBERS_INFO WHERE SALARY IN (SELECT SALARY FROM MEMBERS_INFO WHERE CITY = 'LAHORE');

SELECT *FROM MEMBERS_INFO WHERE SALARY > ALL(SELECT SALARY FROM MEMBERS_INFO WHERE CITY = 'LAHORE');


SELECT *FROM MEMBERS_INFO WHERE SALARY < ALL(SELECT SALARY FROM MEMBERS_INFO WHERE CITY = 'KARACHI');


SELECT *FROM MEMBERS_INFO WHERE SALARY < (SELECT MIN(SALARY) FROM MEMBERS_INFO WHERE CITY = 'KARACHI');



SELECT *FROM MEMBERS_INFO WHERE SALARY = ANY(SELECT SALARY FROM MEMBERS_INFO WHERE CITY = 'LAHORE');

-- 32 SUB QUERIES

SELECT SALARY FROM MEMBERS_INFO WHERE CITY = 'LAHORE';

SELECT SALARY FROM MEMBERS_INFO WHERE SALARY < ANY(SELECT SALARY FROM MEMBERS_INFO WHERE CITY = 'LAHORE');

SELECT *FROM MEMBERS_INFO WHERE CITY = (SELECT CITY FROM MEMBERS_INFO WHERE M_ID = 1);























